jobs:
  checkout_code:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse_js:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn lint
          name: Run ESLint
      - run:
          command: yarn compile
          name: Compile
      - run:
          command: yarn test
          name: Jest
  build_android_debug:
    executor:
      name: android/android
      sdk-version: '28'
      variant: 'node'
    environment:
      - BUILD_THREADS: 2
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - android/install-ndk
      - android/restore-build-cache
      - run:
          name: Start gradle daemon
          working_directory: android
          command: ./gradlew --daemon || true
      - run:
          name: Install gradle dependencies
          working_directory: android
          command: ./gradlew dependencies
      - run:
          name: Set Debug keystore
          command: echo ${DEBUG_KEYSTORE} | base64 -d > android/app/debug.keystore
      - run:
          name: Bundle debug
          working_directory: android
          command: ./gradlew assembleDebug --build-cache --max-workers 2
      - store_artifacts:
          path: android/app/build/outputs/apk
      - android/save-build-cache
orbs:
  android: circleci/android@0.2.0
  rn: react-native-community/react-native@1.2.2
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - hold_build_android_debug:
          type: approval
          requires:
           - analyse_js
      - build_android_debug:
          requires:
            - hold_build_android_debug

