name: Lint and build

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn
    - name: Run ESLint
      run: yarn lint
    - name: Compile
      run: yarn compile
    - name: Jest
      run: yarn test
  build-android:
    needs: lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        java-package: jdk
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn
    - name: Compile
      run: yarn compile
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Download gradle dependencies
      run: ./gradlew dependencies
      working-directory: android
    - name: Set Debug keystore
      run: echo '/u3+7QAAAAIAAAABAAAAAQAPYW5kcm9pZGRlYnVna2V5AAABQ0rLwugAAAUCMIIE/jAOBgorBgEEASoCEQEBBQAEggTqTrf+4E+GStFgPoOC61gnr9bB/F+5FoOnyI/HfwxSOdr5lix4SidLflxqyfw62LKC+H2LAlUpURtdItvcf5/VoQIhgAnIiOXuw5mKEu6dRqw1r0ifeNZB5lyEUKAptdJA5R1JwnPdZJeWPvoyI20B89eZAvSDai84cPPLIiwiyIGoiXxcuNXQ9DFlGrs3ryECxeAVjbhoKIyf9+EuoUZpNdUXu2+GmXVuAWfCKr8hAc3L7K3L23ZGD+cVzdaqilNiIZoOq1TeyTTSGg2vUA08R5XMkYc4nYHNKI/H1achWmQiBgPoGnuKCGum294nXysg8Wux8Qw1b/kcPjmrUi4rNLUvdzNZG5RzyUJ5voIDr/jR8+IwKEoOnilwQuRnzJ2B3VK5XctoCxxULj/HMJ+T7ZLes+jG72tHZ+A99C/ZAxjhtvbvpwkOXlGX/cMR8yIuHU+HUcKWxZfSGIbCAVG1rpVZZysYOBa0+WasJcYA1iJgq1Zm9mKquL4ZTaY2aFerEnGgdMPu/Vt4o9OAHoCqJVxsqMCoWFbxDuf7dX06jgg5jQbIJytO47b4Nzp6XKGdNJcRI78Cnw2UCN9BvkeYmubdmExKYWTvyMmT4M/3ycR7dGJQu9Ge4GzKiUR97kmzGbqPyW0748mII7F0D/o2EARHojshdxGpF99iQOx4ZhwpgUf8RUH/DH81WDggDOGXA3NFf18EPy9mi6Epzfd56COS+X7uRVppV8z2TPuZbWqlmTkp++BMcG8YQhMISUBmwF11+kOB3wf9/DhnfzFCNNbL2Tno7AS4k+NiAgwsyOLWLGLOIIM7mWmDmeOe4SC2IwSnzwa7XiPNHWSTy6L/wIl+5Dx3JUpFrboWDFadMWS4+uMvqf89lataom+kCGye7f1KQzLI5Tg1niU4E2rtb7TRVYQp2PW3oC1uRX0xKB/cEYfhJYqH6TAx2gktIRxJpcNaesZnoAZsNeHgystWxEB2ga3BnD6rG4N41lYBd0x3X6H8yU7D3dNv2Gk3RYYvliiivMRm7DDauGzC0NuFbNvfT26DY9G+HK5kFDjhLEryEQYmTrHPSWjBt1xwTV6KmdF73Hr/+n9UgVqq2rPEcq8bdRbnviiq2fczHHLfPLa5Wba0Af7kDks9jQ+4VpxFBa5v5WWxznXHs+R6tyJkI3gfl2XSe2/y4PHyXDXfb7ABddj0aYhudhRX2eOtQCXH+Dl6/edD5kM69P6GGm1OCEGrgTha13pJF67mZs5TDpoEKBXTnXtyMjky1XCOf3uscE8nKSC7Exy5bTVWG4pMobdbY4HVklRksvGfD50NJ+XuIBtwPg8q5lKWHMEwPk5I9aRjxdbWJ0v82RkCkmRwr1rVa2yIPU5tGksLV6HIp5oSxynOOe7S2sm0QA866KcNowNsm2PB+8Z+vL4QtQ+chdkL7vRHRqsWS49g7a4g7+oY7PR8H67o9D2QF6ea4pYzE1AXKpwuEqi3XHZV1JFki5Gwt9h8tMdIibkFpRt4i6oyvNIaBQXY93CrWufAZ6rJRYnGiCNms3JL8Ovh9UaztEQ4qyLFCA0DVimGbnzu+OOXyrTqMagEBCjSb6IkSsntoeVhg+69XHMM3aY4jyReQCT/UQuVLvB2S930BETqCWWML8GW7aS1jOFRR572Csu6k9Rzso7qyVmAcQAAAAEABVguNTA5AAADfzCCA3swggJjoAMCAQICBCMurmIwDQYJKoZIhvcNAQEFBQAwbTELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB1Vua25vd24xEDAOBgNVBAcTB1Vua25vd24xEDAOBgNVBAoTB1Vua25vd24xEDAOBgNVBAsTB0FuZHJvaWQxFjAUBgNVBAMTDUFuZHJvaWQgRGVidWcwIBcNMTMxMjMxMjIzNTA0WhgPMjA1MjA0MzAyMjM1MDRaMG0xCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRAwDgYDVQQKEwdVbmtub3duMRAwDgYDVQQLEwdBbmRyb2lkMRYwFAYDVQQDEw1BbmRyb2lkIERlYnVnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkt5uICbIbNVEHniMJfQNW9zRd7rXemfDAn3P6K0WP9UVXqRTa1i+GZk2nscWZ3CBhQgdNc3suXEkxOzKzXbhlkKG4IwFiq0v5/g02tFYhAdaW/VIN4dXa/VYh/yYM/s9IZ0pNvFQuYG5OeutT+fZtWHiCFcR04hFSSzUupqrQV+yG4KkddgFc2mH+xc+wMtX8eLmQNmPLeHe6ScAFbDoYzhd2/u2m4fcVQFKiio1WRnRfRVjBbbmsefuAkpxjIkHCJJiQH/UQ95H7/LaSNd0eSsg35MhgEPfmV3NQjdpgMYr/S0jw0+4vi5wrZaGJXgKDuipRUly1E2xJfCG3+nRYQIDAQABoyEwHzAdBgNVHQ4EFgQUC/n+OInSipxY8MEKtw5DKNgj8yAwDQYJKoZIhvcNAQEFBQADggEBAF/SdhW/zmMYTRJQwbkRdfC84vnETnrnd3+NhcnhshU9PRAGa7ABmiwKbX48Atvf93bWtv8nLrz0aCWYaKQMDnfUMEVee8/Duf8vT3qKkxt1sFK79CRfMeKOD0kQGKt+l9f7jh1z0xLNCNyW+53Tk5yi4dat9lz/SljZ7JFq6gbUO1JD+tWc8RRuPHGrZtMk8BKTWjFOlq/4G67Bg8g3kPmahtq1a1vFsm0WlLw1XkKQ7ALtuhFdV7vdZaiw5Gk0VrWsKjoHpER+XXrU3p38ipnFPNTubC5lub/exomujiMZ1ky4OmMIohh+MMA/7vaHcY1JA+VAA6mgtX9429moiSpJHNfTl/MPnoJZYANHJ0BedwjxBQ==' | base64 -d > android/app/debug.keystore
    - name: Build Android debug
      run: ./gradlew assembleDebug
      working-directory: android
    - name: Archive APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: android/app/build/outputs/apk
